import React from 'react'

function HotelRules() {
  return (
    <div className='max-w-screen-xl mx-auto px-[6.05rem] relative -top-8 flex flex-col gap-4 text-[#7A7E9A]'>
      <h1 className='playfair-display text-3xl text-[#24416B]'>HOTEL RULES</h1>
      <p>• ACCOMODATION WILL ONLY BE PROVIDED TO GUESTHOUSE DETAILS ARE REGISTTERED WITH THE HOTEL RECEPTION.</p>
      <p>• GUESTES WILL BE PROVIDED WITH A ROOM KEY ONLY UPON ARRIVAL AND AFTER COMPLETING THE REGISTRATION AT THE HOTELS RECEPTION DESK.</p>
      <p>• PLEASE NOT THAT THE CHECK IN AND KEY COLLECTION TAKE PLACE AT THE HOTEL RECEPTTION ONLY.</p>
      <p>• GUEST ARE REQUIRED TO SHOW A PHOTO INDITIFICATION UPON CHECK IN. PLEASE NOT THAT ALL SPECIAL REQUESTS ARE SUBJECT TO AVAILABILTY AND ADDITIONAL CHAGRES MAY APPLY.</p>
      <p>• GAMBLING, SMOKING,CONTRBAND,SMUGGLED GOODS,PROSTITUATION,WEPONS,EXPLOSIVES,FLAMMABLE OBJECTS, POISONS, DRUNGS,ANIMALS ARE ALL STRICTLY PROHIBITED IN THE HOTEL PREMISES.</p>
      <p>• FOR ANY DAMGES DONE TO THE HOTEL AMITIES,ARTICLES, FURNITURE, PROPERTY ETC BY OR DUE TO GUESTS THEMSELVES OR THEIR VISITORS OR ANY OTHER PERSON FOR WHOM THEY ARE RESPONSIBLE AND SO MUST MAKE UP TO PAY AND SETTLE FOR SUCH LOSS AND DAMAGE IN FULL AS DEEMED APPROPRIATE BY THE MANAGEMENT.</p>
      <p>• VISITORS ENTRY TO THE GUESTS ROOMS STRICTLY PROHIBITED, HOWEVER IN CASE OF EXCEPTIONAL CIRCUMSTANCES THE MANGEMNT MAY ALLOW VISITORS TO GUEST ROOM ONLY AFTER HAVING PHOTO IDENTIFY PROOF DOCUMENTS AND REGISTER ENTRY AT RECEPTION.</p>
      <p>• THE HOTEL MAY DENY FURTHER ACCOMMODATION TO A GUEST WHO DOES NOT PROVE TO BE DECENT AND COMPLY WITH THE HOTEL POLICY AND RULES.</p>
      <p>• ITS IS NOT ALLOWED TO CAUSE ANY DISRURBANCE TO OTHER GUEST OR CAUSE ANY NUISANCE OR ANNOYANCE IN THE HOTEL PREMISES. IT IS AGREEABLY ANTICIPATED THAT GUEST WILL CONDUST THEMSELVES IN A RESPECTABLE , CIVILLIZED AND DECENT.</p>
      <p>• FOR ANY DAMANGE DONE TO THE HOTEL AMENITIES ITEMS OR PROPERTY GUESTES ARE LIABLE TO MAKE UP FOR THE CHARGES IN FULL AND FOR THE AMOUNT AS SEEN APPROPRIATE BY THE MANGEMNT.</p>
      <p>• THE MANGMENT WILL NOT IN ANY WAY WHATSEVER BE RESPONSIBLE FOR ANY LOSS OR DAMAGE TO THE GUESTS BELONGINGS FOR ANY CAUSE WHATSEVER.</p>
      <p>• THE MANGEMENT HAS THE RIGHT TO REQUEST ANY GUEST TO VACATE HIS/HER ROOM OR OTHER AREAS OF THE HOTEL FOT WITH OR WITHOUT PREVIOUS NOTICE AND WITHOUT ASSIGING ANY REASONS WHATSEVER AND THE GUEST SHALL BE BOND TO VACATE WHEN REQUESTED TO DO SO.IN CASE OD DEFULT THE MANGEMENT HAS THE RIGHT TO REMOVE THE GUEST LUGGAGE AND BELONGINGS FROM THE ROOM OCCUPIED BY HIM/HER.</p>
      <p>• THE MANGEMNT RESERVES THE RIGHTS TO ADD OR ALTER OR AMEND ANY OF THE ABOVE POLICY TERMS CONDITIONS AND RULES AT ANY POINT OF TIME WITHOUT PRIOR NOTICE.</p>
    </div>
  )
}

export default HotelRules
